import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../../Sidebar";
import { Toaster } from "@/components/ui/sonner.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"><body
        className={`${geistSans.variable} ${geistMono.variable} antialiased theme-light font-sans`}
      >
        <Sidebar />
        <div className="relative md:pl-64 flex flex-col flex-1">
          <main className="flex-1">{children}</main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
